# Generated by Django 4.2.19 on 2025-02-22 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_foro_inscripcion_progreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curso',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('inactivo', 'Inactivo')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel_dificultad',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='HistorialAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(limit_choices_to={'rol__nombre': 'Administrador'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.curso')),
                ('profesor', models.ForeignKey(limit_choices_to={'rol__nombre': 'Profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
