# Generated by Django 4.2.19 on 2025-02-22 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_nivel_modulo_leccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='comentarios_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leccion',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='RevisionContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('administrador', models.ForeignKey(limit_choices_to={'rol__nombre': 'Administrador'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.leccion')),
            ],
        ),
    ]
